### ISSUE TITLE
Issue with multimodal contexts

### ISSUE THREAD

**Issue by XxTHKxX** [HanaokaYuzu/Gemini-API#2]
I'm seeing some issue with when I'm utilizing stuffs like email integration, for example:

Chat response on web: https://i.imgur.com/lDqbzG7.png

Error on the console:

Traceback (most recent call last):
  File "E:\Python\Others\selfbot-fuve\.venv\lib\site-packages\discord\client.py", line 609, in _run_event
    await coro(*args, **kwargs)
  File "E:\Python\Others\selfbot-fuve\main.py", line 78, in msg
    response = await get_ai_response(content, message.channel.id)
  File "E:\Python\Others\selfbot-fuve\main.py", line 46, in get_ai_response
    response = await chat.send_message(message)
  File "E:\Python\Others\selfbot-fuve\.venv\lib\site-packages\gemini\client.py", line 338, in send_message
    return await self.geminiclient.generate_content(prompt, self)
  File "E:\Python\Others\selfbot-fuve\.venv\lib\site-packages\gemini\client.py", line 38, in wrapper
    return await func(self, *args, **kwargs)
  File "E:\Python\Others\selfbot-fuve\.venv\lib\site-packages\gemini\client.py", line 213, in generate_content
    for candidate in body[4]:
TypeError: 'NoneType' object is not iterable

Seems like there's some stuffs regarding multimodal that's not dealt with yet?

**Comment by jollyolliel** [comment]
Also, I just want to check, can you generate images

**Comment by XxTHKxX** [comment]
Yes, I can generate images on my account, although when I do so via the
API, the response from the AI is that it can't do that yet. Maybe it have
to do with where it's ran from (server in Finland, I'm in Vietnam).

**Comment by HanaokaYuzu** [comment]
Could you install the latest version and try again? Tested with YouTube and Google Workspace extensions and they work fine on my side.

**Comment by XxTHKxX** [comment]
Got it, will try and report back
