### ISSUE TITLE
Bug send content image?

### ISSUE THREAD

**Issue by patricknasci** [HanaokaYuzu/Gemini-API#44]
![image](https://github.com/user-attachments/assets/c4404e4c-3fed-4f70-94d6-1ffe9202a8de)

**Comment by patricknasci** [comment]
`2024-10-20 17:42:37.010 | DEBUG    | gemini_webapi.client:start_auto_refresh:249 - Cookies refreshed. New __Secure-1PSIDTS: sidts-CjEBQlrA-MZcxjPY1Z3YzbUR_foH3aNgGuGwRoJ7vcYpSU0N69QmZyuVfIS628URNpQUEAA
#TEXT:  Hello! How can I help you today?

2024-10-20 17:42:42.848 | DEBUG    | gemini_webapi.client:generate_content:358 - Invalid response: )]}'

[["wrb.fr",null,null,null,null,[13]],["di",405],["af.httprm",405,"-6358397090432126956",29]]
2024-10-20 17:42:46.463 | DEBUG    | gemini_webapi.client:start_auto_refresh:249 - Cookies refreshed. New __Secure-1PSIDTS: None
2024-10-20 17:42:49.643 | DEBUG    | gemini_webapi.client:generate_content:358 - Invalid response: )]}'

[["wrb.fr",null,null,null,null,[13]],["di",380],["af.httprm",379,"7853616991690162906",34]]
2024-10-20 17:42:53.256 | DEBUG    | gemini_webapi.client:start_auto_refresh:249 - Cookies refreshed. New __Secure-1PSIDTS: None
2024-10-20 17:42:56.531 | DEBUG    | gemini_webapi.client:generate_content:358 - Invalid response: )]}'

[["wrb.fr",null,null,null,null,[13]],["di",391],["af.httprm",390,"-2605215677532042506",39]]
Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 348, in generate_content
    body = json.loads(response_json[0][2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 55, in wrapper
    return await func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 359, in generate_content
    raise APIError(
gemini_webapi.exceptions.APIError: Failed to generate contents. Invalid response data received. Client will try to re-initialize on next request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 348, in generate_content
    body = json.loads(response_json[0][2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 48, in wrapper
    return await func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 359, in generate_content
    raise APIError(
gemini_webapi.exceptions.APIError: Failed to generate contents. Invalid response data received. Client will try to re-initialize on next request.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 348, in generate_content
    body = json.loads(response_json[0][2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\test.py", line 28, in <module>
    asyncio.run(main())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.2032.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\test.py", line 20, in main
    response = await client.generate_content(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 59, in wrapper
    return await wrapper(client, *args, retry=retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 59, in wrapper
    return await wrapper(client, *args, retry=retry - 1, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 48, in wrapper
    return await func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Patrick\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\gemini_webapi\client.py", line 359, in generate_content
    raise APIError(
gemini_webapi.exceptions.APIError: Failed to generate contents. Invalid response data received. Client will try to re-initialize on next request.`

**Comment by HanaokaYuzu** [comment]
Sry but could not reproduce. Does this error still exist? If yes, does it occur every time generating contents with image input?

**Comment by patricknasci** [comment]
Yes, when uploading file image to gemini the api returns Invalid response data received

**Comment by HanaokaYuzu** [comment]
Have you tried uploading images on https://gemini.google.com/app to see if it works?

**Comment by patricknasci** [comment]
![image](https://github.com/user-attachments/assets/1ebf50bb-c788-45be-bf1f-fb3901079fda)
Is working.

Run script error
`/lib/python3.12/site-packages/gemini_webapi/client.py", line 348, in generate_content
    body = json.loads(response_json[0][2])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType`

_gemini_webapi.exceptions.APIError: Failed to generate contents. Invalid response data received. Client will try to re-initialize on next request._

**Comment by gr4shin** [comment]
It is already possible to send images, but writes for generation: Failed to parse response body. Data structure is invalid.

**Comment by HanaokaYuzu** [comment]
@patricknasci Could you open web inspector at https://gemini.google.com/app, go to network tab, send message while web inspector is enabled, and then attach the request payload and response of `/StreamGenerate` here?

<img width="1261" alt="Screenshot" src="https://github.com/user-attachments/assets/58da5e00-c92a-4f16-b455-ffb4a34caa1a">

**Comment by HanaokaYuzu** [comment]
Truly weird. I'm getting the same response structure as yours but all tests has passed here without error. Are you running this package on the same device and network as the one you tested in browser? The network environment could be different even on the same host if you are behind a proxy.
